export const SET_AUDIO_PLAYER = "SET_AUDIO_PLAYER";
export const SET_MUSIC_DATA = "SET_MUSIC_DATA";
export const CLEAR_MUSIC_DATA = "CLEAR_MUSIC_DATA";
export const SET_IS_FULLSCREEN = "SET_IS_FULLSCREEN";
