export const PLAYER_SET_AUDIO_PLAYER = "PLAYER_SET_AUDIO_PLAYER";
export const PLAYER_SET_MUSIC_DATA = "PLAYER_SET_MUSIC_DATA";
export const PLAYER_CLEAR_MUSIC_DATA = "PLAYER_CLEAR_MUSIC_DATA";
export const PLAYER_SET_IS_FULLSCREEN = "PLAYER_SET_IS_FULLSCREEN";
export const PLAYER_CLEAR_ALL = "PLAYER_CLEAR_ALL";
