export const PLAYLIST_ADD_TRACK = 'PLAYLIST_ADD_TRACK';
export const PLAYLIST_REMOVE_TRACK = 'PLAYLIST_REMOVE_TRACK';
export const PLAYLIST_SET_CURRENT_TRACK = 'PLAYLIST_SET_CURRENT_TRACK';
export const PLAYLIST_CLEAR_ALL = 'PLAYLIST_CLEAR_ALL';