export const SELECT_ITEM = 'SELECT_ITEM';
export const SET_SELECT_ITEM_LOADING = 'SET_SELECT_ITEM_LOADING';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
