export const SEARCH_SET_ARTISTS = 'SEARCH_SET_ARTISTS';
export const SEARCH_SET_ALBUMS = 'SEARCH_SET_ALBUMS';
export const SEARCH_SET_TRACKS = 'SEARCH_SET_TRACKS';
export const SEARCH_SELECT_ITEM = 'SELECT_ITEM';
