import { SET_SEARCH_RESULTS, SELECT_ITEM } from "../Types/Playlist";

const initialState = {
  searchResults: {
    kind: "youtube#searchListResponse",
    etag: "MZaYGEQZ4vqic_cwPyyW0DyYj8s",
    nextPageToken: "CBQQAA",
    prevPageToken: "CAoQAQ",
    regionCode: "BR",
    pageInfo: { totalResults: 1000000, resultsPerPage: 10 },
    items: [
      {
        kind: "youtube#searchResult",
        etag: "8OhUFoVX774ULSgLpncQgz6KFfc",
        id: { kind: "youtube#video", videoId: "HrQsGeKN6qk" },
        snippet: {
          publishedAt: "2007-11-06T03:10:35Z",
          channelId: "UCxGer6i-a08UT9Cwng7sE7A",
          title: "Chop Suey - System of a Down (lyrics)",
          description:
            "http://youtu.be/XCumTLv7hJM\r\n\r\nLyrics:\r\n\r\nWake up\r\nGrab a brush and put on a little make up\r\nHide the scars to fade away the shakeup\r\nWhyd you leave the keys up on the table\r\nThere you go create another fable\r\nYou wanted to\r\nGrab a brush and put on a little makeup\r\nYou wanted to\r\nHide the scars to fade away the shakeup\r\nYou wanted to\r\nWhyd you leave the keys up on the table\r\nI dont think you trust in my self righteous suicide\r\nI cry when angels deserve to die (die)\r\nWake up\r\nGrab a brush and put on a little make up\r\nHide the scars to fade away the shakeup\r\nWhyd you leave the keys up on the table\r\nThere you go create another fable\r\nYou wanted to\r\nGrab a brush and put on a little makeup\r\nYou wanted to\r\nHide the scars to fade away the shakeup\r\nYou wanted to\r\nWhyd you leave the keys up on the table\r\nI dont think you trust in my self righteous suicide\r\nI cry when angels deserve to die\r\nIn my self righteous suicide\r\nI cry when angels deserve to die\r\nFather father father father\r\nFather into your hand I comend my spirit\r\nFather into your hand why have you forsaken me in your eyes\r\nForsaken me in your thoughts\r\nForsaken me in your heart\r\nForsaken me ohh\r\nTrust in my self righteous suicide\r\nI cry when angels deserve to die\r\nIn my self righteous suicide\r\nI cry when angels deserve to die",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/HrQsGeKN6qk/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/HrQsGeKN6qk/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/HrQsGeKN6qk/hqdefault.jpg",
              width: 480,
              height: 360,
            },
          },
          channelTitle: "blueshockey24",
          tags: ["chop", "suey", "system", "of", "down", "lyrics"],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "Chop Suey - System of a Down (lyrics)",
            description:
              "http://youtu.be/XCumTLv7hJM\r\n\r\nLyrics:\r\n\r\nWake up\r\nGrab a brush and put on a little make up\r\nHide the scars to fade away the shakeup\r\nWhyd you leave the keys up on the table\r\nThere you go create another fable\r\nYou wanted to\r\nGrab a brush and put on a little makeup\r\nYou wanted to\r\nHide the scars to fade away the shakeup\r\nYou wanted to\r\nWhyd you leave the keys up on the table\r\nI dont think you trust in my self righteous suicide\r\nI cry when angels deserve to die (die)\r\nWake up\r\nGrab a brush and put on a little make up\r\nHide the scars to fade away the shakeup\r\nWhyd you leave the keys up on the table\r\nThere you go create another fable\r\nYou wanted to\r\nGrab a brush and put on a little makeup\r\nYou wanted to\r\nHide the scars to fade away the shakeup\r\nYou wanted to\r\nWhyd you leave the keys up on the table\r\nI dont think you trust in my self righteous suicide\r\nI cry when angels deserve to die\r\nIn my self righteous suicide\r\nI cry when angels deserve to die\r\nFather father father father\r\nFather into your hand I comend my spirit\r\nFather into your hand why have you forsaken me in your eyes\r\nForsaken me in your thoughts\r\nForsaken me in your heart\r\nForsaken me ohh\r\nTrust in my self righteous suicide\r\nI cry when angels deserve to die\r\nIn my self righteous suicide\r\nI cry when angels deserve to die",
          },
        },
        contentDetails: {
          duration: "PT3M31S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "55932963",
          likeCount: "339743",
          dislikeCount: "11337",
          favoriteCount: "0",
          commentCount: "25794",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "VzY8E98WZKfZxDZRi8mWNzAJjzI",
        id: { kind: "youtube#video", videoId: "qIDzPUt20F4" },
        snippet: {
          publishedAt: "2007-01-12T02:07:01Z",
          channelId: "UCEyyt1w1XxI6i9me24wBv0g",
          title: "System of a Down Radio/Video",
          description:
            "My weird video to a weird but not less awesome song.Tribute and hint and enjoy^^ (made with Pinnacle Studio)",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/qIDzPUt20F4/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/qIDzPUt20F4/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/qIDzPUt20F4/hqdefault.jpg",
              width: 480,
              height: 360,
            },
          },
          channelTitle: "OlgaJulia",
          tags: [
            "system",
            "of",
            "down",
            "radio",
            "video",
            "soad",
            "clip",
            "videoclip",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "System of a Down Radio/Video",
            description:
              "My weird video to a weird but not less awesome song.Tribute and hint and enjoy^^ (made with Pinnacle Studio)",
          },
        },
        contentDetails: {
          duration: "PT4M13S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "35135202",
          likeCount: "124491",
          dislikeCount: "4824",
          favoriteCount: "0",
          commentCount: "7472",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "e8T0jzRMtmBclUxpY370ciOIWck",
        id: { kind: "youtube#video", videoId: "mkoIiJhnXLo" },
        snippet: {
          publishedAt: "2009-01-05T14:33:36Z",
          channelId: "UC8q-fNBIAk_GNhrWzR78XbA",
          title: "System Of A Down - Lost In Hollywood [with lyrics]",
          description: "S.O.A.D. - Lost in Hollywood ;D",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/mkoIiJhnXLo/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/mkoIiJhnXLo/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/mkoIiJhnXLo/hqdefault.jpg",
              width: 480,
              height: 360,
            },
          },
          channelTitle: "cariret321",
          tags: ["system", "of", "down", "lyrics", "lost", "in", "hollywood"],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "System Of A Down - Lost In Hollywood [with lyrics]",
            description: "S.O.A.D. - Lost in Hollywood ;D",
          },
        },
        contentDetails: {
          duration: "PT5M22S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "28340158",
          likeCount: "120887",
          dislikeCount: "4369",
          favoriteCount: "0",
          commentCount: "8330",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "0_1dg8a0r6nmLBMuuI7Z48IFrL4",
        id: { kind: "youtube#video", videoId: "eyLOw29VJIA" },
        snippet: {
          publishedAt: "2007-10-29T17:03:04Z",
          channelId: "UCKAcRN3dpHJMvEMf2MfzzqA",
          title: "System of a down- Aerials",
          description: "",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/eyLOw29VJIA/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/eyLOw29VJIA/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/eyLOw29VJIA/hqdefault.jpg",
              width: 480,
              height: 360,
            },
          },
          channelTitle: "Xadoo",
          tags: [
            "Lyrics",
            "system",
            "of",
            "down",
            "aerials",
            "s.o.a.d",
            "słowa",
            "Lirics",
            "Xadoo",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: { title: "System of a down- Aerials", description: "" },
        },
        contentDetails: {
          duration: "PT3M57S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "26140423",
          likeCount: "139276",
          dislikeCount: "5202",
          favoriteCount: "0",
          commentCount: "4041",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "S4FFtZ7pTNPY_N8vLg5xF4OKB7w",
        id: { kind: "youtube#video", videoId: "_h7OXPKts_g" },
        snippet: {
          publishedAt: "2012-06-16T15:00:05Z",
          channelId: "UC2BkTYXHQqdm8Y3SJV7v6rw",
          title: "B.Y.O.B. by System Of A Down. Drum Cover- By Kevan Roy",
          description:
            'Kevan was the drummer for Red Lamb for the "Anarchy For Autism" tour with legendary Anthrax guitar player Dan Spitz! To learn more about Kevan and his upcoming projects, follow- http://www.facebook.com/KevanRoyDrumming\nWanna learn techniques for speed and power around the kit from Kevan, directly? Check out http://facebook.com/metaldrummingmastery\n\nAll rights to this song belong to the original artist. Be sure to check them out on itunes!',
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/_h7OXPKts_g/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/_h7OXPKts_g/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/_h7OXPKts_g/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/_h7OXPKts_g/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/_h7OXPKts_g/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "KevanFnRoy",
          tags: [
            "Kevan Roy",
            "Mastery",
            "metal drumming mastery",
            "how to play drums",
            "BYOB",
            "B.Y.O.B.",
            "System Of A Down",
            "B.Y.O.B. drum cover",
            "Red Lamb",
            "Dan Spitz",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "B.Y.O.B. by System Of A Down. Drum Cover- By Kevan Roy",
            description:
              'Kevan was the drummer for Red Lamb for the "Anarchy For Autism" tour with legendary Anthrax guitar player Dan Spitz! To learn more about Kevan and his upcoming projects, follow- http://www.facebook.com/KevanRoyDrumming\nWanna learn techniques for speed and power around the kit from Kevan, directly? Check out http://facebook.com/metaldrummingmastery\n\nAll rights to this song belong to the original artist. Be sure to check them out on itunes!',
          },
        },
        contentDetails: {
          duration: "PT4M29S",
          dimension: "2d",
          definition: "hd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "23325865",
          likeCount: "178907",
          dislikeCount: "6498",
          favoriteCount: "0",
          commentCount: "5624",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "lRrTiOgZryfcRJXENMI10ShQYog",
        id: { kind: "youtube#video", videoId: "jhUSsQ_OXzc" },
        snippet: {
          publishedAt: "2008-05-09T19:05:11Z",
          channelId: "UCk3HTn1i2P70rKGo-aT6Ifw",
          title: "System of a down - Lonely day (lyrics)",
          description: "System of a down\r\nHypnotize (2005)\r\nLonely day",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/jhUSsQ_OXzc/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/jhUSsQ_OXzc/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/jhUSsQ_OXzc/hqdefault.jpg",
              width: 480,
              height: 360,
            },
          },
          channelTitle: "Ermilze",
          tags: ["system", "of", "down", "lonely", "day", "lyrics"],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "System of a down - Lonely day (lyrics)",
            description: "System of a down\r\nHypnotize (2005)\r\nLonely day",
          },
        },
        contentDetails: {
          duration: "PT2M48S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "22122721",
          likeCount: "133586",
          dislikeCount: "2969",
          favoriteCount: "0",
          commentCount: "5456",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "dImSegB8ud8CfBTPbYtE454IcKo",
        id: { kind: "youtube#video", videoId: "bE2r7r7VVic" },
        snippet: {
          publishedAt: "2009-10-03T04:44:17Z",
          channelId: "UCvtZDkeFxMkRTNqfqXtxxkw",
          title: "System Of A Down - Boom! (Official Video)",
          description:
            "System of a Down's official music video for 'Boom!'. Click to listen to System of a Down on Spotify: http://smarturl.it/SystemSpotify?IQid=SystemBoom\n\nAs featured on Steal This Album!. Click to buy the track or album via\niTunes: http://smarturl.it/SystemSTA?IQid=SystemBoom\nGoogle Play: http://smarturl.it/BoomGPlay?IQid=SystemBoom\nAmazon: http://smarturl.it/STAAmazon?IQid=SystemBoom\n\nMore from System of a Down\nChop Suey!: https://youtu.be/CSvFpBOe8eY\nAerials: https://youtu.be/L-iepu3EtyE\nB.Y.O.B: https://youtu.be/zUzd9KyIDrM\n\nMore great Alternative videos here: http://smarturl.it/Alternative00?IQid=SystemBoom\n\nFollow System of a Down\nWebsite: http://www.systemofadown.com/\nFacebook: https://www.facebook.com/systemofadown\nTwitter: https://twitter.com/systemofadown\nInstagram: https://instagram.com/systemofadown/\n\nSubscribe to System of a Down on YouTube: http://smarturl.it/SYODSub?IQid=SystemBoom\n\n---------\n\nLyrics:\n\nI've been walking through your streets,\nWhere all you money's earning,\nWhere all your building's crying,\nAnd clueless neckties working,\nRevolving fake lawn houses,\nHousing all your fears,\nDesensitized by TV,\noverbearing advertising,\nGod of consumerism,\nAnd all your crooked pictures,\nLooking good, mirrorism,\nFiltering information,\nFor the public eye,\nDesigned for profiteering,\nYour neighboor, what a guy.\n\nBOOM, BOOM, BOOM, BOOM,\nEvery time you drop the bomb,\nYou kill the god your child has born.\nBOOM, BOOM, BOOM, BOOM.",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/bE2r7r7VVic/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/bE2r7r7VVic/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/bE2r7r7VVic/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/bE2r7r7VVic/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/bE2r7r7VVic/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "systemofadownVEVO",
          tags: [
            "lonely day",
            "Boom lyrics",
            "byob",
            "System of a Down lyrics",
            "acoustic",
            "System of a Down live",
            "music",
            "mezmerize",
            "System of a Down",
            "vevo",
            "steal this album",
            "official",
            "download",
            "aerials",
            "remix",
            "lyrics",
            "official video",
            "cover",
            "System of a Down Boom official",
            "spiders",
            "Boom live",
            "sugar",
            "original",
            "Sony",
            "hypnotize",
            "music video",
            "single",
            "toxicity",
            "album",
            "full album",
            "System of a Down Boom",
            "chop suey",
            "live",
            "SystemofaDownVevo",
            "American/Columbia",
            "Boom!",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "System Of A Down - Boom! (Official Video)",
            description:
              "System of a Down's official music video for 'Boom!'. Click to listen to System of a Down on Spotify: http://smarturl.it/SystemSpotify?IQid=SystemBoom\n\nAs featured on Steal This Album!. Click to buy the track or album via\niTunes: http://smarturl.it/SystemSTA?IQid=SystemBoom\nGoogle Play: http://smarturl.it/BoomGPlay?IQid=SystemBoom\nAmazon: http://smarturl.it/STAAmazon?IQid=SystemBoom\n\nMore from System of a Down\nChop Suey!: https://youtu.be/CSvFpBOe8eY\nAerials: https://youtu.be/L-iepu3EtyE\nB.Y.O.B: https://youtu.be/zUzd9KyIDrM\n\nMore great Alternative videos here: http://smarturl.it/Alternative00?IQid=SystemBoom\n\nFollow System of a Down\nWebsite: http://www.systemofadown.com/\nFacebook: https://www.facebook.com/systemofadown\nTwitter: https://twitter.com/systemofadown\nInstagram: https://instagram.com/systemofadown/\n\nSubscribe to System of a Down on YouTube: http://smarturl.it/SYODSub?IQid=SystemBoom\n\n---------\n\nLyrics:\n\nI've been walking through your streets,\nWhere all you money's earning,\nWhere all your building's crying,\nAnd clueless neckties working,\nRevolving fake lawn houses,\nHousing all your fears,\nDesensitized by TV,\noverbearing advertising,\nGod of consumerism,\nAnd all your crooked pictures,\nLooking good, mirrorism,\nFiltering information,\nFor the public eye,\nDesigned for profiteering,\nYour neighboor, what a guy.\n\nBOOM, BOOM, BOOM, BOOM,\nEvery time you drop the bomb,\nYou kill the god your child has born.\nBOOM, BOOM, BOOM, BOOM.",
          },
          defaultAudioLanguage: "en-US",
        },
        contentDetails: {
          duration: "PT3M2S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: true,
          regionRestriction: {
            allowed: [
              "GI",
              "GH",
              "GN",
              "GM",
              "GL",
              "GB",
              "GA",
              "GG",
              "GF",
              "GE",
              "GD",
              "GY",
              "GS",
              "GR",
              "GQ",
              "GP",
              "GW",
              "GU",
              "GT",
              "UA",
              "PL",
              "WS",
              "CZ",
              "WF",
              "NP",
              "FI",
              "FJ",
              "FK",
              "FM",
              "FO",
              "PF",
              "NZ",
              "NA",
              "NC",
              "NE",
              "NF",
              "NG",
              "NI",
              "FR",
              "PE",
              "NL",
              "NO",
              "UM",
              "VU",
              "VI",
              "VN",
              "VA",
              "VC",
              "VE",
              "VG",
              "EC",
              "EE",
              "EG",
              "EH",
              "ZW",
              "ZM",
              "ES",
              "ER",
              "ET",
              "LR",
              "ZA",
              "LS",
              "NU",
              "MH",
              "MK",
              "MM",
              "ML",
              "MO",
              "MN",
              "MA",
              "MC",
              "UZ",
              "ME",
              "MD",
              "MG",
              "MF",
              "MY",
              "MX",
              "MZ",
              "OM",
              "UG",
              "MQ",
              "MP",
              "MS",
              "MR",
              "MU",
              "MT",
              "MW",
              "MV",
              "LV",
              "DO",
              "LT",
              "LU",
              "DJ",
              "DK",
              "SV",
              "CL",
              "DE",
              "LY",
              "DZ",
              "LC",
              "LA",
              "LK",
              "LI",
              "TZ",
              "TV",
              "TW",
              "TT",
              "TR",
              "TN",
              "TO",
              "TL",
              "TM",
              "TJ",
              "TK",
              "TH",
              "TF",
              "LB",
              "TD",
              "TC",
              "CG",
              "PK",
              "PH",
              "CD",
              "PN",
              "CA",
              "PM",
              "CO",
              "CN",
              "CM",
              "PA",
              "CK",
              "PG",
              "CI",
              "CH",
              "CW",
              "CV",
              "CU",
              "PY",
              "CR",
              "PR",
              "PS",
              "PW",
              "CY",
              "CX",
              "KN",
              "KM",
              "ST",
              "SS",
              "SR",
              "KI",
              "KH",
              "KG",
              "KE",
              "SZ",
              "SY",
              "SX",
              "SG",
              "SE",
              "SD",
              "SC",
              "SB",
              "KY",
              "KW",
              "SN",
              "SM",
              "SL",
              "SK",
              "KR",
              "SI",
              "SH",
              "BD",
              "BE",
              "BF",
              "BG",
              "SA",
              "BB",
              "BL",
              "BM",
              "BN",
              "BO",
              "BH",
              "BI",
              "BJ",
              "BT",
              "SO",
              "BV",
              "BW",
              "BQ",
              "BR",
              "BS",
              "BY",
              "BZ",
              "JM",
              "RW",
              "RS",
              "JE",
              "SJ",
              "RE",
              "KZ",
              "RO",
              "JP",
              "AX",
              "DM",
              "AZ",
              "AU",
              "AT",
              "AW",
              "AQ",
              "NR",
              "AS",
              "AR",
              "AM",
              "AL",
              "AO",
              "AI",
              "AE",
              "AD",
              "AG",
              "JO",
              "CF",
              "BA",
              "IE",
              "ID",
              "AF",
              "IM",
              "IL",
              "IO",
              "IN",
              "IT",
              "IQ",
              "IS",
              "IR",
              "YT",
              "HT",
              "QA",
              "US",
              "RU",
              "YE",
              "PT",
              "TG",
              "KP",
              "HK",
              "HN",
              "HM",
              "HR",
              "UY",
              "CC",
              "HU",
            ],
          },
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "21884903",
          likeCount: "102952",
          dislikeCount: "2546",
          favoriteCount: "0",
          commentCount: "8803",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "_VigoUWuP86Gzj_36nOnDFjgDpk",
        id: { kind: "youtube#video", videoId: "nVZ8tRlcZhA" },
        snippet: {
          publishedAt: "2007-05-16T17:50:37Z",
          channelId: "UCjGl6z20r088zU52pmw7deg",
          title: "System Of A Down - Atwa",
          description:
            "From System of a Downs second album Toxicity....no vid. just music",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/nVZ8tRlcZhA/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/nVZ8tRlcZhA/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/nVZ8tRlcZhA/hqdefault.jpg",
              width: 480,
              height: 360,
            },
          },
          channelTitle: "blackheartedsoab",
          tags: ["System", "OfA", "Down", "Atwa", "soad"],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "System Of A Down - Atwa",
            description:
              "From System of a Downs second album Toxicity....no vid. just music",
          },
        },
        contentDetails: {
          duration: "PT3M",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "18432476",
          likeCount: "86208",
          dislikeCount: "2211",
          favoriteCount: "0",
          commentCount: "3856",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "KDi6qsIVoprPG7-6hbpo08Qq-rk",
        id: { kind: "youtube#video", videoId: "F46r-_jPPHY" },
        snippet: {
          publishedAt: "2009-10-03T04:47:18Z",
          channelId: "UCvtZDkeFxMkRTNqfqXtxxkw",
          title: "System Of A Down - War? (Official Video)",
          description:
            "System of a Down's official music video for 'War?'. Click to listen to System of a Down on Spotify: http://smarturl.it/SystemSpotify?IQid=SystemWar\n\nAs featured on System of a Down. Click to buy the track or album via\niTunes: http://smarturl.it/SystemSOAD?IQid=SystemWar\nGoogle Play: http://smarturl.it/SYODWarGPlay?IQid=SystemWar\nAmazon: http://smarturl.it/SOADAmazon?IQid=SystemWar\n\nMore from System of a Down\nChop Suey!: https://youtu.be/CSvFpBOe8eY\nAerials: https://youtu.be/L-iepu3EtyE\nB.Y.O.B: https://youtu.be/zUzd9KyIDrM\n\nMore great Alternative videos here: http://smarturl.it/Alternative00?IQid=SystemWar\n\nFollow System of a Down\nWebsite: http://www.systemofadown.com/\nFacebook: https://www.facebook.com/systemofadown\nTwitter: https://twitter.com/systemofadown\nInstagram: https://instagram.com/systemofadown/\n\nSubscribe to System of a Down on YouTube: http://smarturl.it/SYODSub?IQid=SystemWar\n\n---------\n\nLyrics:\n\nDark is the light, \nThe man you fight, \nWith all your prayers, incantations, \nRunning away, a trivial day, \nOf judgement and deliverance, \nTo whom was sold, this bounty soul, \nA gentile or a priest? \nWho victored over, the Seljuks, \nWhen the Holy Land was taken \nWe will fight the heathens, \nWe will fight the heathens \nWe will fight the heathens, \nWe will fight the heathens \nWas it the riches, of the land, \nPowers of bright darkness, \nThat led the noble, to the East, \nTo fight the heathens \nWe will fight the heathens,",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/F46r-_jPPHY/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/F46r-_jPPHY/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/F46r-_jPPHY/hqdefault.jpg",
              width: 480,
              height: 360,
            },
            standard: {
              url: "https://i.ytimg.com/vi/F46r-_jPPHY/sddefault.jpg",
              width: 640,
              height: 480,
            },
            maxres: {
              url: "https://i.ytimg.com/vi/F46r-_jPPHY/maxresdefault.jpg",
              width: 1280,
              height: 720,
            },
          },
          channelTitle: "systemofadownVEVO",
          tags: [
            "System of a Down War",
            "lonely day",
            "byob",
            "System of a Down lyrics",
            "acoustic",
            "System of a Down live",
            "music",
            "mezmerize",
            "System of a Down",
            "vevo",
            "steal this album",
            "System of a Down War official",
            "official",
            "download",
            "aerials",
            "remix",
            "War lyrics",
            "lyrics",
            "official video",
            "cover",
            "spiders",
            "sugar",
            "original",
            "Sony",
            "hypnotize",
            "music video",
            "single",
            "toxicity",
            "album",
            "full album",
            "War live",
            "chop suey",
            "live",
            "SystemofaDownVevo",
            "American",
            "Metal/Hard Rock",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "System Of A Down - War? (Official Video)",
            description:
              "System of a Down's official music video for 'War?'. Click to listen to System of a Down on Spotify: http://smarturl.it/SystemSpotify?IQid=SystemWar\n\nAs featured on System of a Down. Click to buy the track or album via\niTunes: http://smarturl.it/SystemSOAD?IQid=SystemWar\nGoogle Play: http://smarturl.it/SYODWarGPlay?IQid=SystemWar\nAmazon: http://smarturl.it/SOADAmazon?IQid=SystemWar\n\nMore from System of a Down\nChop Suey!: https://youtu.be/CSvFpBOe8eY\nAerials: https://youtu.be/L-iepu3EtyE\nB.Y.O.B: https://youtu.be/zUzd9KyIDrM\n\nMore great Alternative videos here: http://smarturl.it/Alternative00?IQid=SystemWar\n\nFollow System of a Down\nWebsite: http://www.systemofadown.com/\nFacebook: https://www.facebook.com/systemofadown\nTwitter: https://twitter.com/systemofadown\nInstagram: https://instagram.com/systemofadown/\n\nSubscribe to System of a Down on YouTube: http://smarturl.it/SYODSub?IQid=SystemWar\n\n---------\n\nLyrics:\n\nDark is the light, \nThe man you fight, \nWith all your prayers, incantations, \nRunning away, a trivial day, \nOf judgement and deliverance, \nTo whom was sold, this bounty soul, \nA gentile or a priest? \nWho victored over, the Seljuks, \nWhen the Holy Land was taken \nWe will fight the heathens, \nWe will fight the heathens \nWe will fight the heathens, \nWe will fight the heathens \nWas it the riches, of the land, \nPowers of bright darkness, \nThat led the noble, to the East, \nTo fight the heathens \nWe will fight the heathens,",
          },
          defaultAudioLanguage: "en-US",
        },
        contentDetails: {
          duration: "PT3M12S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: true,
          regionRestriction: {
            allowed: [
              "GI",
              "GH",
              "GN",
              "GM",
              "GL",
              "GB",
              "GA",
              "GG",
              "GF",
              "GE",
              "GD",
              "GY",
              "GS",
              "GR",
              "GQ",
              "GP",
              "GW",
              "GU",
              "GT",
              "UA",
              "PL",
              "WS",
              "CZ",
              "WF",
              "NP",
              "FI",
              "FJ",
              "FK",
              "FM",
              "FO",
              "PF",
              "NZ",
              "NA",
              "NC",
              "NE",
              "NF",
              "NG",
              "NI",
              "FR",
              "PE",
              "NL",
              "NO",
              "UM",
              "VU",
              "VI",
              "VN",
              "VA",
              "VC",
              "VE",
              "VG",
              "EC",
              "EE",
              "EG",
              "EH",
              "ZW",
              "ZM",
              "ES",
              "ER",
              "ET",
              "LR",
              "ZA",
              "LS",
              "NU",
              "MH",
              "MK",
              "MM",
              "ML",
              "MO",
              "MN",
              "MA",
              "MC",
              "UZ",
              "ME",
              "MD",
              "MG",
              "MF",
              "MY",
              "MX",
              "MZ",
              "OM",
              "UG",
              "MQ",
              "MP",
              "MS",
              "MR",
              "MU",
              "MT",
              "MW",
              "MV",
              "LV",
              "DO",
              "LT",
              "LU",
              "DJ",
              "DK",
              "SV",
              "CL",
              "DE",
              "LY",
              "DZ",
              "LC",
              "LA",
              "LK",
              "LI",
              "TZ",
              "TV",
              "TW",
              "TT",
              "TR",
              "TN",
              "TO",
              "TL",
              "TM",
              "TJ",
              "TK",
              "TH",
              "TF",
              "LB",
              "TD",
              "TC",
              "CG",
              "PK",
              "PH",
              "CD",
              "PN",
              "CA",
              "PM",
              "CO",
              "CN",
              "CM",
              "PA",
              "CK",
              "PG",
              "CI",
              "CH",
              "CW",
              "CV",
              "CU",
              "PY",
              "CR",
              "PR",
              "PS",
              "PW",
              "CY",
              "CX",
              "KN",
              "KM",
              "ST",
              "SS",
              "SR",
              "KI",
              "KH",
              "KG",
              "KE",
              "SZ",
              "SY",
              "SX",
              "SG",
              "SE",
              "SD",
              "SC",
              "SB",
              "KY",
              "KW",
              "SN",
              "SM",
              "SL",
              "SK",
              "KR",
              "SI",
              "SH",
              "BD",
              "BE",
              "BF",
              "BG",
              "SA",
              "BB",
              "BL",
              "BM",
              "BN",
              "BO",
              "BH",
              "BI",
              "BJ",
              "BT",
              "SO",
              "BV",
              "BW",
              "BQ",
              "BR",
              "BS",
              "BY",
              "BZ",
              "JM",
              "RW",
              "RS",
              "JE",
              "SJ",
              "RE",
              "KZ",
              "RO",
              "JP",
              "AX",
              "DM",
              "AZ",
              "AU",
              "AT",
              "AW",
              "AQ",
              "NR",
              "AS",
              "AR",
              "AM",
              "AL",
              "AO",
              "AI",
              "AE",
              "AD",
              "AG",
              "JO",
              "CF",
              "BA",
              "IE",
              "ID",
              "AF",
              "IM",
              "IL",
              "IO",
              "IN",
              "IT",
              "IQ",
              "IS",
              "IR",
              "YT",
              "HT",
              "QA",
              "US",
              "RU",
              "YE",
              "PT",
              "TG",
              "KP",
              "HK",
              "HN",
              "HM",
              "HR",
              "UY",
              "CC",
              "HU",
            ],
          },
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "17337051",
          likeCount: "87695",
          dislikeCount: "1735",
          favoriteCount: "0",
          commentCount: "5854",
        },
      },
      {
        kind: "youtube#searchResult",
        etag: "9Z_Ad8459A5wqi_A-q8TJKXFg4Y",
        id: { kind: "youtube#video", videoId: "UVaPFtVx8PA" },
        snippet: {
          publishedAt: "2007-03-11T09:18:18Z",
          channelId: "UCedgV0O-VfqQk-qN6PLBDrQ",
          title: "System Of A Down - Revenga",
          description:
            "This song is from System of a down's 4th album Mezmerize, and the video contains clips from the following videos:\n\n- Core\n- AVP\n- Underworld\n- Matrix Reloaded\n- Matrix Revolutions\n- Tomb Raider (Cradle of Life)\n- Dawn of the Dead\n- Resident Evil",
          thumbnails: {
            default: {
              url: "https://i.ytimg.com/vi/UVaPFtVx8PA/default.jpg",
              width: 120,
              height: 90,
            },
            medium: {
              url: "https://i.ytimg.com/vi/UVaPFtVx8PA/mqdefault.jpg",
              width: 320,
              height: 180,
            },
            high: {
              url: "https://i.ytimg.com/vi/UVaPFtVx8PA/hqdefault.jpg",
              width: 480,
              height: 360,
            },
          },
          channelTitle: "untuned20",
          tags: [
            "System",
            "Down",
            "SOAD",
            "Revenga",
            "Core",
            "Alien",
            "Vs",
            "Predator",
            "Matrix",
          ],
          categoryId: "10",
          liveBroadcastContent: "none",
          localized: {
            title: "System Of A Down - Revenga",
            description:
              "This song is from System of a down's 4th album Mezmerize, and the video contains clips from the following videos:\n\n- Core\n- AVP\n- Underworld\n- Matrix Reloaded\n- Matrix Revolutions\n- Tomb Raider (Cradle of Life)\n- Dawn of the Dead\n- Resident Evil",
          },
        },
        contentDetails: {
          duration: "PT3M48S",
          dimension: "2d",
          definition: "sd",
          caption: "false",
          licensedContent: false,
          contentRating: {},
          projection: "rectangular",
        },
        statistics: {
          viewCount: "16504863",
          likeCount: "39265",
          dislikeCount: "1560",
          favoriteCount: "0",
          commentCount: "2417",
        },
      },
    ],
  },
  selectedItem: null,
};

function reducer(state = initialState, action) {
  switch (action.type) {
    case SET_SEARCH_RESULTS: {
      return {
        ...state,
        searchResults: action.payload,
      };
    }

    case SELECT_ITEM: {
      return {
        ...state,
        selectedItem: action.payload,
      };
    }

    default:
      return state;
  }
}

export default reducer;
